# terraform
name: Deploy Infraestructura Azure

on:
  push:
    paths:
      - 'infra/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesión en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Inicializar Terraform
        run: terraform -chdir=infra init

      - name: Planificar infraestructura
        run: terraform -chdir=infra plan -out main.tfplan

      - name: Aplicar infraestructura
        run: terraform -chdir=infra apply -auto-approve main.tfplan
